//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "medical_appointments")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub user_id: i32,
  pub patient_id: i32,
  pub practitioner_office_id: i32,
  pub date: Date,
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::patients::Entity",
    from = "Column::PatientId",
    to = "super::patients::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Patients,
  #[sea_orm(
    belongs_to = "super::practitioner_offices::Entity",
    from = "Column::PractitionerOfficeId",
    to = "super::practitioner_offices::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  PractitionerOffices,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::UserId",
    to = "super::users::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::patients::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Patients.def()
  }
}

impl Related<super::practitioner_offices::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::PractitionerOffices.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}
