//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod medical_appointments;
pub mod patients;
pub mod practitioner_offices;
pub mod user_business_informations;
pub mod user_practitioner_offices;
pub mod users;
