//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "office")]
pub enum Office {
  #[sea_orm(string_value = "Vitry-sur-Seine")]
  VitrySurSeine,
  #[sea_orm(string_value = "Rueil-Malmaison")]
  RueilMalmaison,
}
