export const PROFESSIONS = [
  "general_practitioner",
  "pediatrician",
  "gynecologist",
  "psychiatrist",
  "gastroenterologist",
  "ent_specialist",
  "endocrinologist",
  "cardiologist",
  "angiologist",
  "nephrologist",
  "neurologist",
  "pulmonologist",
  "rheumatologist",
  "dermatologist",
  "dentist",
  "midwife",
  "physiotherapist",
  "nurse",
  "psychologist",
  "osteopath",
  "audiologist",
  "chiropractor",
  "genetic_counselor",
  "dietitian",
  "occupational_therapist",
  "speech_therapist",
  "orthoptist",
  "podiatrist",
  "psychomotrician",
  "psychotherapist",
] as const;

export type Profession = (typeof PROFESSIONS)[number];
